using System.Text.Json;
using Profitable.Core.Content;
using Profitable.Core.Schema;
using Profitable.Core.Simulation;

namespace ProfitableCore.Tests.Parity;

// Agent 40 (Unity Galaxy/Planet Parity Validation) --
// docs/agents/agent-40-unity-galaxy-planet-parity-validation.md.
//
// Reads unity/parity/ts-parity-results.json's galaxy/planet-generation
// sections (generated by `npm run parity` against the REAL content/*.json
// catalog) and re-runs every case through the C# port, asserting exact
// equality -- the strongest possible proof that SeededRandom,
// PlanetGenerator, ResourceSubsetSelector, PlanetQualityRoller, and
// PlanetResourceCycle all agree with the TypeScript source end-to-end,
// not just per-function.
public class GalaxyPlanetParityTests
{
    private static string FixturePath(string fileName) =>
        Path.Combine(AppContext.BaseDirectory, "Fixtures", fileName);

    private static readonly Lazy<List<Resource>> RealResources = new(() =>
        ContentLoader.LoadFromFiles(
            FixturePath("resources.json"),
            FixturePath("recipes.json"),
            FixturePath("refiningRecipes.json"),
            FixturePath("schematics.json"),
            FixturePath("planets.json")).Resources);

    private static ParityCorpus LoadCorpus()
    {
        var path = Path.Combine(AppContext.BaseDirectory, "Parity", "ts-parity-results.json");
        var json = File.ReadAllText(path);
        return JsonSerializer.Deserialize<ParityCorpus>(json)
            ?? throw new InvalidOperationException("failed to deserialize ts-parity-results.json");
    }

    private static TierColor ParseTier(string name) => Enum.Parse<TierColor>(name);
    private static PlanetType ParsePlanetType(string name) => Enum.Parse<PlanetType>(name);

    private static void AssertQualityMapMatches(Dictionary<string, int?> expected, QualityMap actual)
    {
        foreach (var quality in Qualities.All)
        {
            var key = Qualities.ToJsonName(quality);
            var expectedValue = expected.TryGetValue(key, out var v) ? v : null;
            var actualValue = actual.TryGetValue(quality, out var av) ? av : null;
            Assert.True(expectedValue == actualValue, $"quality '{key}': expected {expectedValue?.ToString() ?? "null"}, got {actualValue?.ToString() ?? "null"}");
        }
    }

    private static void AssertResourceQualitiesMatch(
        Dictionary<string, Dictionary<string, int?>> expected,
        Dictionary<string, QualityMap> actual)
    {
        Assert.Equal(expected.Keys.OrderBy(k => k), actual.Keys.OrderBy(k => k));
        foreach (var (id, expectedRoll) in expected)
        {
            AssertQualityMapMatches(expectedRoll, actual[id]);
        }
    }

    // Per-Resource Quantity Caps.
    private static void AssertResourceQuantityCapsMatch(
        Dictionary<string, int?> expected,
        Dictionary<string, int?> actual)
    {
        Assert.Equal(expected.Keys.OrderBy(k => k), actual.Keys.OrderBy(k => k));
        foreach (var (id, expectedCap) in expected)
        {
            var actualCap = actual.TryGetValue(id, out var v) ? v : null;
            Assert.True(expectedCap == actualCap, $"resource '{id}': expected cap {expectedCap?.ToString() ?? "null"}, got {actualCap?.ToString() ?? "null"}");
        }
    }

    private static void AssertPlanetMatches(SerializedPlanet expected, Planet actual)
    {
        Assert.Equal(expected.Id, actual.Id);
        Assert.Equal(expected.Name, actual.Name);
        Assert.Equal(expected.PlanetType is null ? (PlanetType?)null : ParsePlanetType(expected.PlanetType), actual.PlanetType);
        Assert.Equal(expected.Tier is null ? (TierColor?)null : ParseTier(expected.Tier), actual.Tier);
        if (expected.Position is null)
        {
            Assert.Null(actual.Position);
        }
        else
        {
            Assert.NotNull(actual.Position);
            Assert.Equal(expected.Position.X, actual.Position!.X);
            Assert.Equal(expected.Position.Y, actual.Position!.Y);
        }
        Assert.Equal(expected.ProducibleResourceIds, actual.ProducibleResourceIds);
        Assert.Equal(expected.SpecialtyResourceId, actual.SpecialtyResourceId);
        Assert.Equal(expected.Discovered, actual.Discovered);
        AssertResourceQualitiesMatch(expected.ResourceQualities, actual.ResourceQualities ?? new Dictionary<string, QualityMap>());
    }

    public static IEnumerable<object[]> GalaxyCases() =>
        LoadCorpus().GalaxyCases.Select(c => new object[] { c });

    [Theory]
    [MemberData(nameof(GalaxyCases))]
    public void GenerateGalaxyMatchesTypeScript(GalaxyCase testCase)
    {
        var galaxy = GalaxyGenerator.Generate(testCase.PlanetCount, RealResources.Value, testCase.Seed);

        Assert.Equal(testCase.ExpectedGalaxy.Seed, galaxy.Seed);
        Assert.Equal(testCase.ExpectedGalaxy.Planets.Count, galaxy.Planets.Count);
        for (var i = 0; i < testCase.ExpectedGalaxy.Planets.Count; i++)
        {
            AssertPlanetMatches(testCase.ExpectedGalaxy.Planets[i], galaxy.Planets[i]);
        }
    }

    public static IEnumerable<object[]> PlanetResourceCycleCases() =>
        LoadCorpus().PlanetResourceCycleCases.Select(c => new object[] { c });

    [Theory]
    [MemberData(nameof(PlanetResourceCycleCases))]
    public void GenerateResourcesForCycleMatchesTypeScript(PlanetResourceCycleCase testCase)
    {
        var result = PlanetResourceCycle.GenerateResourcesForCycle(
            testCase.Seed,
            ParseTier(testCase.Tier),
            ParsePlanetType(testCase.PlanetType),
            RealResources.Value,
            testCase.CycleIndex);

        Assert.Equal(testCase.ExpectedResult.ProducibleResourceIds, result.ProducibleResourceIds);
        Assert.Equal(testCase.ExpectedResult.SpecialtyResourceId, result.SpecialtyResourceId);
        AssertResourceQualitiesMatch(testCase.ExpectedResult.ResourceQualities, result.ResourceQualities);
        AssertResourceQuantityCapsMatch(testCase.ExpectedResult.ResourceQuantityCaps, result.ResourceQuantityCaps);
    }

    public static IEnumerable<object[]> GcprCases() =>
        LoadCorpus().GcprCases.Select(c => new object[] { c });

    [Theory]
    [MemberData(nameof(GcprCases))]
    public void GetCurrentPlanetResourcesMatchesTypeScript(GcprCase testCase)
    {
        var planet = new Planet
        {
            Id = testCase.Planet.Id,
            Name = testCase.Planet.Name,
            ProducibleResourceIds = testCase.Planet.ProducibleResourceIds,
            PlanetType = testCase.Planet.PlanetType is null ? null : ParsePlanetType(testCase.Planet.PlanetType),
            Tier = testCase.Planet.Tier is null ? null : ParseTier(testCase.Planet.Tier),
            SpecialtyResourceId = testCase.Planet.SpecialtyResourceId,
            ColonistCount = testCase.Planet.ColonistCount,
        };

        var result = PlanetResourceCycle.GetCurrentPlanetResources(planet, RealResources.Value, testCase.NowMs, testCase.IsStartingPlanet);

        Assert.Equal(testCase.ExpectedResult.ProducibleResourceIds, result.ProducibleResourceIds);
        Assert.Equal(testCase.ExpectedResult.SpecialtyResourceId, result.SpecialtyResourceId);
        AssertResourceQualitiesMatch(testCase.ExpectedResult.ResourceQualities, result.ResourceQualities);
        AssertResourceQuantityCapsMatch(testCase.ExpectedResult.ResourceQuantityCaps, result.ResourceQuantityCaps);
    }
}
