using System.Text.Json;
using Profitable.Core.Schema;
using Profitable.Core.Simulation;
using ProfitableCore.Tests.Simulation;

namespace ProfitableCore.Tests.Parity;

// Agent 33 (Unity Parity Validation) -- docs/agents/agent-33-unity-parity-validation.md.
//
// Reads unity/parity/ts-parity-results.json (generated by `npm run
// parity`, which runs the REAL TypeScript functions) and re-runs every
// case through the C# port with the identical recorded random sequence,
// asserting exact equality. This is what actually proves numeric parity
// -- ProfitableCore.Tests/Simulation/*Tests.cs mirror the TypeScript
// suite's hand-copied expected values, which is a weaker claim (see this
// agent's own Responsibility section for why).
public class ParityTests
{
    private static readonly Dictionary<string, Resource> ResourcesById = new()
    {
        ["igneous-ore"] = TestFixtures.IgneousOre,
        ["hydrogen-gas"] = TestFixtures.HydrogenGas,
        ["autunite-crystal"] = TestFixtures.AutuniteCrystal,
        ["radiant-alloy-bar"] = TestFixtures.RadiantAlloyBar,
    };

    private static readonly Dictionary<string, Recipe> RecipesById = new()
    {
        ["ion-forged-hull-plate"] = TestFixtures.IonForgedHullPlateRecipe,
        ["test-no-threshold"] = TestFixtures.NoThresholdRecipe,
    };

    private static ParityCorpus LoadCorpus()
    {
        var path = Path.Combine(AppContext.BaseDirectory, "Parity", "ts-parity-results.json");
        var json = File.ReadAllText(path);
        return JsonSerializer.Deserialize<ParityCorpus>(json)
            ?? throw new InvalidOperationException("failed to deserialize ts-parity-results.json");
    }

    private static QualityMap ToQualityMap(Dictionary<string, int?> raw)
    {
        var map = new QualityMap();
        foreach (var quality in Qualities.All)
        {
            var key = Qualities.ToJsonName(quality);
            map[quality] = raw.TryGetValue(key, out var value) ? value : null;
        }
        return map;
    }

    private static ResourceInstance ToInstance(SerializedInstance serialized) => new()
    {
        Resource = ResourcesById[serialized.ResourceId],
        Quantity = serialized.Quantity,
        Qualities = ToQualityMap(serialized.Qualities),
    };

    private static TierColor ParseTier(string name) => Enum.Parse<TierColor>(name);

    private static void AssertQualitiesMatch(Dictionary<string, int?> expected, QualityMap actual)
    {
        foreach (var quality in Qualities.All)
        {
            var key = Qualities.ToJsonName(quality);
            var expectedValue = expected.TryGetValue(key, out var v) ? v : null;
            Assert.True(
                expectedValue == actual[quality],
                $"quality '{key}': expected {expectedValue?.ToString() ?? "null"}, got {actual[quality]?.ToString() ?? "null"}");
        }
    }

    public static IEnumerable<object[]> TierColorCases() =>
        LoadCorpus().TierColorCases.Select(c => new object[] { c.Value, c.ExpectedTier });

    [Theory]
    [MemberData(nameof(TierColorCases))]
    public void GetTierColorMatchesTypeScript(double value, string expectedTier)
    {
        Assert.Equal(ParseTier(expectedTier), TierColorResolver.GetTierColor(value));
    }

    public static IEnumerable<object[]> RollQualityCases() =>
        LoadCorpus().RollQualityCases.Select(c => new object[] { c });

    [Theory]
    [MemberData(nameof(RollQualityCases))]
    public void RollQualityMatchesTypeScript(RollQualityCase testCase)
    {
        var resource = ResourcesById[testCase.ResourceId];
        var random = TestFixtures.QueueRandom(testCase.RandomSequence.ToArray());

        var actual = QualityRoller.RollQuality(resource, random);

        AssertQualitiesMatch(testCase.ExpectedRoll, actual);
    }

    public static IEnumerable<object[]> RefineCases() =>
        LoadCorpus().RefineCases.Select(c => new object[] { c });

    [Theory]
    [MemberData(nameof(RefineCases))]
    public void RefineMatchesTypeScript(RefineCase testCase)
    {
        var inputs = testCase.Inputs.Select(ToInstance).ToList();
        var refinerTier = ParseTier(testCase.RefinerTier);
        var random = TestFixtures.QueueRandom(testCase.RandomSequence.ToArray());

        var actual = Refiner.Refine(inputs, refinerTier, random);

        AssertQualitiesMatch(testCase.ExpectedResult.Qualities, actual.Qualities);
        Assert.Equal(ParseTier(testCase.ExpectedResult.OutputTier), actual.OutputTier);
        Assert.Equal(testCase.ExpectedResult.RefundUnits, actual.RefundUnits);
    }

    public static IEnumerable<object[]> CraftCases() =>
        LoadCorpus().CraftCases.Select(c => new object[] { c });

    [Theory]
    [MemberData(nameof(CraftCases))]
    public void CraftMatchesTypeScript(CraftCase testCase)
    {
        var inputs = testCase.Inputs.Select(ToInstance).ToList();
        var recipe = RecipesById[testCase.RecipeId];
        var schematicTier = ParseTier(testCase.SchematicTier);
        var crafterTier = ParseTier(testCase.CrafterTier);
        var random = TestFixtures.QueueRandom(testCase.RandomSequence.ToArray());

        var actual = Crafter.Craft(inputs, recipe, schematicTier, crafterTier, random);

        Assert.Equal(testCase.ExpectedResult.Accepted, actual.Accepted);
        if (testCase.ExpectedResult.Accepted)
        {
            var accepted = Assert.IsType<CraftAccepted>(actual);
            Assert.NotNull(testCase.ExpectedResult.Qualities);
            AssertQualitiesMatch(testCase.ExpectedResult.Qualities!, accepted.Qualities);
        }
        else
        {
            var rejected = Assert.IsType<CraftRejected>(actual);
            Assert.Equal(testCase.ExpectedResult.Reason, rejected.Reason);
        }
    }
}
