using System.Text.Json;
using Profitable.Core.Content;
using Profitable.Core.Schema;
using Profitable.Core.Simulation;

namespace ProfitableCore.Tests.Parity;

// Agent 45 (Unity Trading Parity Validation) --
// docs/agents/agent-45-unity-trading-parity-validation.md.
//
// Reads unity/parity/ts-parity-results.json's Sub-Phase B (Trading)
// sections (generated by `npm run parity` against the real content
// catalog) and re-runs every case through the C# port, asserting exact
// equality -- the same "the C# code agrees with the TypeScript code, not
// merely with itself" standard Agent 33/40 already established.
public class TradingParityTests
{
    private static string FixturePath(string fileName) =>
        Path.Combine(AppContext.BaseDirectory, "Fixtures", fileName);

    private static readonly Lazy<List<Resource>> RealResources = new(() =>
        ContentLoader.LoadFromFiles(
            FixturePath("resources.json"),
            FixturePath("recipes.json"),
            FixturePath("refiningRecipes.json"),
            FixturePath("schematics.json"),
            FixturePath("planets.json")).Resources);

    private static Resource FindResource(string id) => RealResources.Value.First(r => r.Id == id);

    private static ParityCorpus LoadCorpus()
    {
        var path = Path.Combine(AppContext.BaseDirectory, "Parity", "ts-parity-results.json");
        var json = File.ReadAllText(path);
        return JsonSerializer.Deserialize<ParityCorpus>(json)
            ?? throw new InvalidOperationException("failed to deserialize ts-parity-results.json");
    }

    private static QualityMap ToQualityMap(Dictionary<string, int?> raw)
    {
        var map = new QualityMap();
        foreach (var quality in Qualities.All)
        {
            var key = Qualities.ToJsonName(quality);
            map[quality] = raw.TryGetValue(key, out var value) ? value : null;
        }
        return map;
    }

    private static void AssertQualitiesMatch(Dictionary<string, int?> expected, QualityMap actual)
    {
        foreach (var quality in Qualities.All)
        {
            var key = Qualities.ToJsonName(quality);
            var expectedValue = expected.TryGetValue(key, out var v) ? v : null;
            var actualValue = actual.TryGetValue(quality, out var av) ? av : null;
            Assert.True(expectedValue == actualValue, $"quality '{key}': expected {expectedValue?.ToString() ?? "null"}, got {actualValue?.ToString() ?? "null"}");
        }
    }

    private static ResourceInstance ToInstance(SerializedInstance serialized) => new()
    {
        Resource = FindResource(serialized.ResourceId),
        Quantity = serialized.Quantity,
        Qualities = ToQualityMap(serialized.Qualities),
    };

    // MarketLocation has no single natural JSON shape (the TypeScript
    // union serializes as either the bare string "global" or the object
    // { planetId }) -- parsed here from the raw JsonElement rather than
    // via a custom JsonConverter, matching this test suite's existing
    // "manual reconstruction from DTO into real domain object" convention
    // (see GalaxyPlanetParityTests.AssertPlanetMatches).
    private static MarketLocation ParseLocation(JsonElement element) =>
        element.ValueKind == JsonValueKind.String
            ? GlobalMarketLocation.Instance
            : new PlanetMarketLocation { PlanetId = element.GetProperty("planetId").GetString()! };

    private static TradeDirection ParseDirection(string raw) => raw switch
    {
        "buy" => TradeDirection.Buy,
        "sell" => TradeDirection.Sell,
        _ => throw new InvalidOperationException($"unknown TradeDirection '{raw}'"),
    };

    private static ReturnDestination ParseDestination(string raw) => raw switch
    {
        "planet-pickup" => ReturnDestination.PlanetPickup,
        "inventory" => ReturnDestination.Inventory,
        _ => throw new InvalidOperationException($"unknown ReturnDestination '{raw}'"),
    };

    private static Listing ToListing(SerializedListing serialized) => new()
    {
        Id = serialized.Id,
        ItemId = serialized.ItemId,
        Quantity = serialized.Quantity,
        PricePerUnit = serialized.PricePerUnit,
        MarketTier = Enum.Parse<TierColor>(serialized.MarketTier),
        Location = ParseLocation(serialized.Location),
        CreatedByPlayerId = serialized.CreatedByPlayerId,
        CreatedAt = serialized.CreatedAt,
        ExpiresAt = serialized.ExpiresAt,
    };

    private static void AssertLocationMatches(JsonElement expected, MarketLocation actual)
    {
        if (expected.ValueKind == JsonValueKind.String)
        {
            Assert.True(actual.IsGlobal);
        }
        else
        {
            Assert.False(actual.IsGlobal);
            Assert.Equal(expected.GetProperty("planetId").GetString(), ((PlanetMarketLocation)actual).PlanetId);
        }
    }

    private static void AssertListingMatches(SerializedListing expected, Listing actual)
    {
        Assert.Equal(expected.Id, actual.Id);
        Assert.Equal(expected.ItemId, actual.ItemId);
        Assert.Equal(expected.Quantity, actual.Quantity);
        Assert.Equal(expected.PricePerUnit, actual.PricePerUnit);
        Assert.Equal(expected.MarketTier, actual.MarketTier.ToString());
        AssertLocationMatches(expected.Location, actual.Location);
        Assert.Equal(expected.CreatedByPlayerId, actual.CreatedByPlayerId);
        Assert.Equal(expected.CreatedAt, actual.CreatedAt);
        Assert.Equal(expected.ExpiresAt, actual.ExpiresAt);
    }

    private static PlanetMarketState ToMarketState(SerializedMarketState serialized) => new()
    {
        PlanetId = serialized.PlanetId,
        ItemId = serialized.ItemId,
        CurrentPrice = serialized.CurrentPrice,
        BasePrice = serialized.BasePrice,
    };

    private static void AssertMarketStateMatches(SerializedMarketState expected, PlanetMarketState actual)
    {
        Assert.Equal(expected.PlanetId, actual.PlanetId);
        Assert.Equal(expected.ItemId, actual.ItemId);
        Assert.Equal(expected.CurrentPrice, actual.CurrentPrice, precision: 10);
        Assert.Equal(expected.BasePrice, actual.BasePrice, precision: 10);
    }

    private static Wallet ToWallet(SerializedWallet serialized) => new() { PlayerId = serialized.PlayerId, Credits = serialized.Credits };

    private static void AssertWalletMatches(SerializedWallet expected, Wallet actual)
    {
        Assert.Equal(expected.PlayerId, actual.PlayerId);
        Assert.Equal(expected.Credits, actual.Credits, precision: 10);
    }

    public static IEnumerable<object[]> CreateListingCases() =>
        LoadCorpus().CreateListingCases.Select(c => new object[] { c });

    [Theory]
    [MemberData(nameof(CreateListingCases))]
    public void CreateListingMatchesTypeScript(CreateListingCase testCase)
    {
        var instance = ToInstance(testCase.ItemInstance);
        var location = ParseLocation(testCase.Location);

        var listing = ListingFactory.CreateListing(instance, testCase.Quantity, testCase.PricePerUnit, location, testCase.PlayerId, testCase.Id, testCase.NowMs);

        AssertListingMatches(testCase.ExpectedListing, listing);
    }

    public static IEnumerable<object[]> ApplyDriftCases() =>
        LoadCorpus().ApplyDriftCases.Select(c => new object[] { c });

    [Theory]
    [MemberData(nameof(ApplyDriftCases))]
    public void ApplyDriftMatchesTypeScript(ApplyDriftCase testCase)
    {
        var result = Drift.ApplyDrift(ToMarketState(testCase.MarketState), testCase.UnitsTraded, ParseDirection(testCase.Direction));
        AssertMarketStateMatches(testCase.ExpectedMarketState, result);
    }

    public static IEnumerable<object[]> ApplyRecoveryCases() =>
        LoadCorpus().ApplyRecoveryCases.Select(c => new object[] { c });

    [Theory]
    [MemberData(nameof(ApplyRecoveryCases))]
    public void ApplyRecoveryMatchesTypeScript(ApplyRecoveryCase testCase)
    {
        var result = Drift.ApplyRecovery(ToMarketState(testCase.MarketState), testCase.ElapsedHours);
        AssertMarketStateMatches(testCase.ExpectedMarketState, result);
    }

    public static IEnumerable<object[]> SeasonCases() =>
        LoadCorpus().SeasonCases.Select(c => new object[] { c });

    [Theory]
    [MemberData(nameof(SeasonCases))]
    public void SeasonMatchesTypeScript(SeasonCase testCase)
    {
        var season = SeasonSimulation.GetCurrentSeason(testCase.PlanetId, testCase.NowMs);
        Assert.Equal(testCase.ExpectedSeason, season.ToString());

        var effect = SeasonSimulation.GetSeasonalEffect(testCase.PlanetId, testCase.NowMs, testCase.Categories);
        if (testCase.ExpectedEffect is null)
        {
            Assert.Null(effect);
        }
        else
        {
            Assert.NotNull(effect);
            Assert.Equal(testCase.ExpectedEffect.Season, effect!.Season.ToString());
            Assert.Equal(testCase.ExpectedEffect.CheapCategory, effect.CheapCategory);
            Assert.Equal(testCase.ExpectedEffect.PremiumCategory, effect.PremiumCategory);
        }

        if (testCase.Categories.Count > 0)
        {
            var multiplier = SeasonSimulation.GetSeasonalPriceMultiplier(testCase.Categories[0], effect);
            Assert.Equal(testCase.ExpectedMultiplierForFirstCategory!.Value, multiplier, precision: 10);
        }
    }

    public static IEnumerable<object[]> EmergencyCases() =>
        LoadCorpus().EmergencyCases.Select(c => new object[] { c });

    [Theory]
    [MemberData(nameof(EmergencyCases))]
    public void EmergencyMatchesTypeScript(EmergencyCase testCase)
    {
        var emergency = Emergency.GetActiveEmergency(testCase.PlanetId, testCase.NowMs, testCase.Categories);
        if (testCase.ExpectedEmergency is null)
        {
            Assert.Null(emergency);
        }
        else
        {
            Assert.NotNull(emergency);
            Assert.Equal(testCase.ExpectedEmergency.Category, emergency!.Category);
            Assert.Equal(testCase.ExpectedEmergency.EndsAt, emergency.EndsAt);
        }

        if (testCase.Categories.Count > 0)
        {
            var multiplier = Emergency.GetEmergencyPriceMultiplier(testCase.Categories[0], emergency);
            Assert.Equal(testCase.ExpectedMultiplierForFirstCategory!.Value, multiplier, precision: 10);
        }
    }

    public static IEnumerable<object[]> GlobalPriceCases() =>
        LoadCorpus().GlobalPriceCases.Select(c => new object[] { c });

    [Theory]
    [MemberData(nameof(GlobalPriceCases))]
    public void GlobalPriceMatchesTypeScript(GlobalPriceCase testCase)
    {
        var marketStates = testCase.MarketStates.Select(ToMarketState).ToList();
        var price = GlobalPrice.GetGlobalPrice(testCase.ItemId, ParseDirection(testCase.Direction), marketStates);
        Assert.Equal(testCase.ExpectedPrice, price, precision: 10);
    }

    public static IEnumerable<object[]> PurchaseListingCases() =>
        LoadCorpus().PurchaseListingCases.Select(c => new object[] { c });

    [Theory]
    [MemberData(nameof(PurchaseListingCases))]
    public void PurchaseListingMatchesTypeScript(PurchaseListingCase testCase)
    {
        var listing = ToListing(testCase.Listing);
        var marketState = testCase.MarketState is null ? null : ToMarketState(testCase.MarketState);

        var result = PurchaseListingSimulation.PurchaseListing(listing, testCase.QuantityToBuy, testCase.BuyerPlayerId, marketState);

        Assert.Equal(testCase.ExpectedResult.Success, result.Success);
        if (result is PurchaseSucceeded succeeded)
        {
            Assert.True(testCase.ExpectedResult.Success);
            AssertListingMatches(testCase.ExpectedResult.UpdatedListing!, succeeded.UpdatedListing);
            Assert.Equal(testCase.ExpectedResult.Closed, succeeded.Closed);
            Assert.Equal(testCase.ExpectedResult.QuantityPurchased, succeeded.QuantityPurchased);
            Assert.Equal(testCase.ExpectedResult.TotalPaid!.Value, succeeded.TotalPaid, precision: 10);
            Assert.Equal(testCase.ExpectedResult.FeeDeducted!.Value, succeeded.FeeDeducted, precision: 10);
            Assert.Equal(testCase.ExpectedResult.ProceedsToSeller!.Value, succeeded.ProceedsToSeller, precision: 10);
            if (testCase.ExpectedResult.UpdatedMarketState is null)
            {
                Assert.Null(succeeded.UpdatedMarketState);
            }
            else
            {
                Assert.NotNull(succeeded.UpdatedMarketState);
                AssertMarketStateMatches(testCase.ExpectedResult.UpdatedMarketState, succeeded.UpdatedMarketState!);
            }
        }
        else
        {
            var rejected = Assert.IsType<PurchaseRejected>(result);
            Assert.Equal(testCase.ExpectedResult.Reason, rejected.Reason);
        }
    }

    public static IEnumerable<object[]> SellToMarketCases() =>
        LoadCorpus().SellToMarketCases.Select(c => new object[] { c });

    [Theory]
    [MemberData(nameof(SellToMarketCases))]
    public void SellToMarketMatchesTypeScript(SellToMarketCase testCase)
    {
        var result = SellToMarketSimulation.SellToMarket(
            ToInstance(testCase.ItemInstance), testCase.Quantity, ToMarketState(testCase.MarketState), ToWallet(testCase.Wallet), testCase.SellerPlayerId);

        Assert.Equal(testCase.ExpectedResult.QuantitySold, result.QuantitySold);
        Assert.Equal(testCase.ExpectedResult.TotalValue, result.TotalValue, precision: 10);
        Assert.Equal(testCase.ExpectedResult.FeeDeducted, result.FeeDeducted, precision: 10);
        Assert.Equal(testCase.ExpectedResult.ProceedsToSeller, result.ProceedsToSeller, precision: 10);
        AssertWalletMatches(testCase.ExpectedResult.UpdatedWallet, result.UpdatedWallet);
        AssertMarketStateMatches(testCase.ExpectedResult.UpdatedMarketState, result.UpdatedMarketState);
    }

    public static IEnumerable<object[]> SellToGlobalMarketCases() =>
        LoadCorpus().SellToGlobalMarketCases.Select(c => new object[] { c });

    [Theory]
    [MemberData(nameof(SellToGlobalMarketCases))]
    public void SellToGlobalMarketMatchesTypeScript(SellToGlobalMarketCase testCase)
    {
        var marketStates = testCase.MarketStates.Select(ToMarketState).ToList();
        var result = SellToGlobalMarketSimulation.SellToGlobalMarket(
            ToInstance(testCase.ItemInstance), testCase.Quantity, marketStates, ToWallet(testCase.Wallet), testCase.SellerPlayerId);

        Assert.Equal(testCase.ExpectedResult.QuantitySold, result.QuantitySold);
        Assert.Equal(testCase.ExpectedResult.TotalValue, result.TotalValue, precision: 10);
        Assert.Equal(testCase.ExpectedResult.FeeDeducted, result.FeeDeducted, precision: 10);
        Assert.Equal(testCase.ExpectedResult.ProceedsToSeller, result.ProceedsToSeller, precision: 10);
        AssertWalletMatches(testCase.ExpectedResult.UpdatedWallet, result.UpdatedWallet);
    }

    public static IEnumerable<object[]> ExpireListingsCases() =>
        LoadCorpus().ExpireListingsCases.Select(c => new object[] { c });

    [Theory]
    [MemberData(nameof(ExpireListingsCases))]
    public void ExpireListingsMatchesTypeScript(ExpireListingsCase testCase)
    {
        var listings = testCase.Listings.Select(ToListing).ToList();
        var result = ExpireListingsSimulation.ExpireListings(listings, testCase.CurrentTimeMs);

        Assert.Equal(testCase.ExpectedResult.Expired.Count, result.Expired.Count);
        for (var i = 0; i < result.Expired.Count; i++)
        {
            AssertListingMatches(testCase.ExpectedResult.Expired[i], result.Expired[i]);
        }

        Assert.Equal(testCase.ExpectedResult.Returned.Count, result.Returned.Count);
        for (var i = 0; i < result.Returned.Count; i++)
        {
            var expected = testCase.ExpectedResult.Returned[i];
            var actual = result.Returned[i];
            Assert.Equal(expected.ItemId, actual.ItemId);
            Assert.Equal(expected.Quantity, actual.Quantity);
            Assert.Equal(expected.PlayerId, actual.PlayerId);
            Assert.Equal(ParseDestination(expected.Destination), actual.Destination);
            Assert.Equal(expected.PlanetId, actual.PlanetId);
        }
    }
}
